window.eway=window.eway||{};
window.eway.GoogleMapTooltip=function(b,c,a){this._oTarget=c;this._sTooltipUniqueId=generateUUID();c&&(this._sTooltipUniqueId+="_"+c.__gm_id);this._sTooltipDivId="yui-tooltip-"+this._sTooltipUniqueId;this._oTargetPosition=null;a=a||{};void 0==a.stickOnTargetClick&&(a.stickOnTargetClick=!0);a.stickOnTargetClick=!!a.stickOnTargetClick;void 0==a.showOnMouseOver&&(a.showOnMouseOver=!0);a.showOnMouseOver=!!a.showOnMouseOver;a.showOnMouseOver||(a.stickOnTargetClick=!0);void 0==a.showCloseButton&&(a.showCloseButton=
!1);a.showCloseButton=!!a.showCloseButton;a.handlePosition=a.handlePosition||"bottom";null=={top:1,bottom:1,left:1,right:1,"top-left":1,"top-right":1,"bottom-left":1,"bottom-right":1,"left-top":1,"left-bottom":1,"right-top":1,"right-bottom":1}[a.handlePosition]&&(console.log("GOOGLE MAP YUI TOOLTIP NOTICE: Wrong handlePosition value '"+a.handlePosition+"' for '"+c+"' tooltip. handlePosition is set to 'bottom'."),a.handlePosition="bottom");c=a.handlePosition.split("-");a.sTooltipPos=c[0];a.sArrowPos=
null;2==c.length&&(a.sArrowPos=c[1]);a.iArrowIndent=12;void 0==a.appearAfterTime&&(a.appearAfterTime=100);a.appearAfterTime=checkIntegerOptionValue(a.appearAfterTime);void 0==a.disappearAfterTime&&(a.disappearAfterTime=100);a.disappearAfterTime=checkIntegerOptionValue(a.disappearAfterTime);void 0==a.holdOnMouseOver&&(a.holdOnMouseOver=!0);a.holdOnMouseOver=!!a.holdOnMouseOver;a.holdOnMouseOver&&100>a.disappearAfterTime&&(a.disappearAfterTime=100);void 0==a.appearTime&&(a.appearTime=100);a.appearTime=
checkIntegerOptionValue(a.appearTime);0==a.appearTime&&(a.appearTime=1);a.appearTime/=1E3;void 0==a.disappearTime&&(a.disappearTime=100);a.disappearTime=checkIntegerOptionValue(a.disappearTime);0==a.disappearTime&&(a.disappearTime=1);a.disappearTime/=1E3;void 0==a.opacity&&(a.opacity=0.9);a.opacity=parseFloat(a.opacity);isNaN(a.opacity)&&(a.opacity=0.9);void 0==a.width&&(a.width=0);a.width=parseFloat(a.width);isNaN(a.width)&&(a.width=0);void 0==a.tooltipIndent&&(a.tooltipIndent=10);a.tooltipIndent=
parseFloat(a.tooltipIndent);isNaN(a.tooltipIndent)&&(a.tooltipIndent=10);void 0==a.tooltipHorizontalIndent&&(a.tooltipHorizontalIndent=0);a.tooltipHorizontalIndent=parseFloat(a.tooltipHorizontalIndent);isNaN(a.tooltipHorizontalIndent)&&(a.tooltipHorizontalIndent=0);void 0==a.hideOnSecondClick&&(a.hideOnSecondClick=!1);a.hideOnSecondClick=!!a.hideOnSecondClick;void 0==a.stayVisible&&(a.stayVisible=!1);a.stayVisible=!!a.stayVisible;void 0!==a.position&&(this._oTargetPosition=a.position,this._oTarget=
null);void 0!==a.map&&(this._oMap=a.map,this._oTarget=null);void 0===a.beforeTooltipShow&&(a.beforeTooltipShow=null);void 0===a.afterTooltipCreated&&(a.afterTooltipCreated=null);void 0!==a.contentUrl&&(a.getContentFromUrl=!0);void 0!==a.noContentPadding&&(a.noContentPadding=!0);a.hideArrow=a.hideArrow?!0:!1;void 0!==a.jquery&&(a.jquery=a.jquery);void 0!==a.contentUrlParams&&(a.contentUrlParams=a.contentUrlParams);void 0==a.refreshContent&&(a.refreshContent=!0);a.refreshContent=!!a.refreshContent;
this._oOptions=a;this._oTarget||(this._oOptions.stayVisible=!0);this._sContent=b||"";this._aTargetEventsListeners=this._aTooltipEventsListeners=this._closeButtonListener=this._oTooltipDiv=null;this._bNotDisapear=this._bTooltipIsShown=!1;this._bAllowToFadeOut=!0;this._bPanTooltip=!1;this._refreshContentTimer=null};window.eway.GoogleMapTooltip.prototype=new google.maps.OverlayView;
window.eway.GoogleMapTooltip.prototype.setTooltip=function(){if(this._oTargetPosition&&!this._oMap||!this._oTargetPosition&&this._oMap)console.log("GOOGLE MAP YUI TOOLTIP NOTICE: map and position options must be together");else{var b=this;this._aTargetEventsListeners=[];this._oOptions.stayVisible&&(b.open(),b._oOptions.hideOnSecondClick&&(b._bNotDisapear=!0));this._oTarget&&(this._oOptions.showOnMouseOver?this._aTargetEventsListeners.push(google.maps.event.addListener(b._oTarget,"mouseover",function(){b._bTooltipIsShown||
b.open();b._bAllowToFadeOut=!1})):this._oOptions.hideOnSecondClick||(this._bNotDisapear=!0),this._oOptions.stickOnTargetClick&&this._aTargetEventsListeners.push(google.maps.event.addListener(b._oTarget,"click",function(){b._bNotDisapear=b._oOptions.hideOnSecondClick?!b._bNotDisapear:!0;b._oOptions.showOnMouseOver||(b._bNotDisapear?b.open():b.close());b.pan()})),this._aTargetEventsListeners.push(google.maps.event.addListener(b._oTarget,"mouseout",function(){b._oOptions.showOnMouseOver&&(setTimeout(function(){b._bAllowToFadeOut&&
!b._bNotDisapear&&b._fadeOut()},b._oOptions.disappearAfterTime),b._bAllowToFadeOut=!0)})))}};window.eway.GoogleMapTooltip.prototype.destroy=function(){this.close();if(this._aTargetEventsListeners){for(var b=0;b<this._aTargetEventsListeners.length;b++)google.maps.event.removeListener(this._aTargetEventsListeners[b]);this._aTargetEventsListeners=null}};
window.eway.GoogleMapTooltip.prototype._createTooltipDiv=function(){var b,c=this,a=function(a){a.cancelBubble=!0;a.stopPropagation()};if(!this._oTooltipDiv){this._oTooltipDiv=document.createElement("div");0!==this._oOptions.width&&(this._oTooltipDiv.style.width=this._oOptions.width+"px");this._oTooltipDiv.style.position="absolute";this._oTooltipDiv.style.zIndex="1000002";this._oTooltipDiv.style.visibility="hidden";this._oTooltipDiv.id=this._sTooltipDivId;b="yui-tooltip-content";this._oOptions.noContentPadding&&
(b+="-nopadding");this._oTooltipDiv.innerHTML='<DIV id="'+this._sTooltipDivId+'_body" class="yui-tooltip-body yui-tooltip-'+c._oOptions.sTooltipPos+'"><DIV id="yui-tooltip-'+this._sTooltipUniqueId+'subarrow" class="yui-tooltip-subarrow yui-tooltip-subarrow-'+c._oOptions.sTooltipPos+'"></DIV><DIV id="yui-tooltip-'+this._sTooltipUniqueId+'arrow" class="yui-tooltip-arrow yui-tooltip-arrow-'+c._oOptions.sTooltipPos+'"></DIV><DIV class="'+b+'" id="yui-tooltip-'+this._sTooltipUniqueId+'content"><DIV id="yui-tooltip-'+
this._sTooltipUniqueId+'content-close-button" class="yui-tooltip-content-close-button"></DIV><DIV id="yui-tooltip-'+this._sTooltipUniqueId+'content-text">'+this._sContent+"</DIV></DIV></DIV>";this.getPanes().floatPane.appendChild(this._oTooltipDiv);this._oOptions.afterTooltipCreated&&this._oOptions.afterTooltipCreated();this._oOptions.showCloseButton?this.addClickHandler_():(b=document.getElementById("yui-tooltip-"+this._sTooltipUniqueId+"content-close-button"),b.parentNode.removeChild(b));this._aTooltipEventsListeners=
[];b="scrollwheel DOMMouseScroll mousewheel contextmenu mousemove mousedown mouseover mouseout mouseenter mouseup click dblclick touchstart touchend touchmove".split(" ");for(i=0;i<b.length;i++)this._aTooltipEventsListeners.push(google.maps.event.addDomListener(this._oTooltipDiv,b[i],a));this._aTooltipEventsListeners.push(google.maps.event.addDomListener(this._oTooltipDiv,"mouseover",function(a){this.style.cursor="default";c._oOptions.holdOnMouseOver&&(c._bAllowToFadeOut=!1)}));c._oOptions.holdOnMouseOver&&
this._aTooltipEventsListeners.push(google.maps.event.addDomListener(this._oTooltipDiv,"mouseout",function(a){setTimeout(function(){!c._bAllowToFadeOut||c._bNotDisapear||c._oOptions.stayVisible||c._fadeOut()},c._oOptions.disappearAfterTime);c._bAllowToFadeOut=!0}));c._setArrowPosition()}};
window.eway.GoogleMapTooltip.prototype._fadeIn=function(){if(this._oTooltipDiv){var b=this;setTimeout(function(){b._oTooltipDiv&&(b._oTooltipDiv.style.visibility="visible",b._oTooltipDiv.style.opacity=0,YUI().use("node","event","anim",function(c){c=new c.Anim({node:b._oTooltipDiv,from:{opacity:0},to:{opacity:b._oOptions.opacity},duration:b._oOptions.appearTime,easing:c.Easing.easeNone});c.on("end",function(){b._oTooltipDiv&&(b._bTooltipIsShown=!0)});c.run()}))},b._oOptions.appearAfterTime)}};
window.eway.GoogleMapTooltip.prototype._fadeOut=function(){this._refreshContentTimer&&(clearInterval(this._refreshContentTimer),this._refreshContentTimer=null);if(this._oTooltipDiv){var b=this;YUI().use("node","event","anim",function(c){c=new c.Anim({node:b._oTooltipDiv,to:{opacity:0},duration:b._oOptions.disappearTime,easing:c.Easing.easeNone});c.on("end",function(){b._oTooltipDiv&&(b.close(),b._bTooltipIsShown=!1)});c.run()})}};
window.eway.GoogleMapTooltip.prototype.addClickHandler_=function(){var b=document.getElementById("yui-tooltip-"+this._sTooltipUniqueId+"content-close-button");this._closeButtonListener=google.maps.event.addDomListener(b,"click",this.getCloseClickHandler_())};window.eway.GoogleMapTooltip.prototype.getCloseClickHandler_=function(){var b=this;return function(c){c.cancelBubble=!0;setTimeout(function(){b._fadeOut()},b._oOptions.disappearAfterTime);b._bNotDisapear=!1}};
window.eway.GoogleMapTooltip.prototype.onRemove=function(){this._oTooltipDiv&&(this._oTooltipDiv.parentNode.removeChild(this._oTooltipDiv),this._oTooltipDiv=null)};
window.eway.GoogleMapTooltip.prototype.draw=function(){this._createTooltipDiv();var b=this;if(b._oOptions.getContentFromUrl){YUI().use("node",function(a){a.one("#yui-tooltip-"+b._sTooltipUniqueId+"content-text").setHTML("<DIV class='loading_div'></DIV>");b._setTooltipPosition();b._setArrowPosition();if(a=document.getElementById("yui-tooltip-"+b._sTooltipUniqueId+"content-close-button"))a.style.visibility="hidden"});var c=function(){b._oOptions.jquery.getJSON(b._oOptions.contentUrl,b._oOptions.contentUrlParams,
function(a){YUI().use("node",function(c){var e=b.onMapResized(a.a),e=e.html;if(c=c.one("#yui-tooltip-"+b._sTooltipUniqueId+"content-text"))if(c.setHTML(e),b._setTooltipPosition(),b._setArrowPosition(),b._oOptions.showCloseButton&&(e=document.getElementById("yui-tooltip-"+b._sTooltipUniqueId+"content-close-button")))e.style.visibility="visible"})})};c();b._refreshContentTimer&&(clearInterval(b._refreshContentTimer),b._refreshContentTimer=null);b._oOptions.refreshContent&&(b._refreshContentTimer=setInterval(c,
21E3));b._bPanTooltip=!1}this._setTooltipPosition();this._oTooltipDiv.style.visibility="hidden";this._fadeIn()};
window.eway.GoogleMapTooltip.prototype._setTooltipPosition=function(){var b=this.getProjection();if(b){var b=b.fromLatLngToDivPixel(this._oTargetPosition),c=b.x,a=b.y,f=null,e=null,d=this;YUI().use("node",function(b){var g=b.one("#"+d._sTooltipDivId+"_body"),k=g.get("offsetWidth"),q=g.get("offsetHeight"),g=parseInt(g.getStyle("paddingTop"));switch(d._oOptions.sTooltipPos){case "left":f=a-q/2;e=c-k-d._oOptions.tooltipIndent;break;case "right":f=a-q/2;e=c+d._oOptions.tooltipIndent;break;case "top":f=
a-q-d._oOptions.tooltipIndent;e=c-k/2-d._oOptions.tooltipHorizontalIndent;break;case "bottom":f=a+d._oOptions.tooltipIndent,e=c-k/2-d._oOptions.tooltipHorizontalIndent}switch(d._oOptions.sArrowPos){case "left":e=e+k/2-d._oOptions.iArrowIndent-g;break;case "right":e=e-k/2+d._oOptions.iArrowIndent+g;break;case "top":f=f+q/2-d._oOptions.iArrowIndent-g;break;case "bottom":f=f-q/2+d._oOptions.iArrowIndent+g}b.one(d._oTooltipDiv).setStyle("left",e);b.one(d._oTooltipDiv).setStyle("top",f);d._oTooltipPosition=
{left:e,top:f};d._oTooltipSize={height:q,width:k};d._bPanTooltip&&d.pan()})}};
window.eway.GoogleMapTooltip.prototype._setArrowPosition=function(){var b=document.getElementById("yui-tooltip-"+this._sTooltipUniqueId+"arrow");if(b)if(!0==this._oOptions.hideArrow)b.parentNode.removeChild(b),b=document.getElementById("yui-tooltip-"+this._sTooltipUniqueId+"subarrow"),b.parentNode.removeChild(b);else{b.style.top=null;b.style.bottom=null;b.style.left=null;b.style.right=null;var c=document.getElementById("yui-tooltip-"+this._sTooltipUniqueId+"content");if(null===this._oOptions.sArrowPos)switch(this._oOptions.sTooltipPos){case "bottom":case "top":c=
c.offsetWidth;b.style.left=Math.floor(c/2)+"px";break;case "left":case "right":c=c.offsetHeight,b.style.top=Math.floor(c/2)+"px"}else b.style[this._oOptions.sArrowPos]=this._oOptions.iArrowIndent+"px";b=document.getElementById("yui-tooltip-"+this._sTooltipUniqueId+"subarrow");b.style.top=null;b.style.bottom=null;b.style.left=null;b.style.right=null;c=document.getElementById("yui-tooltip-"+this._sTooltipUniqueId+"content");if(null===this._oOptions.sArrowPos)switch(this._oOptions.sTooltipPos){case "bottom":case "top":c=
c.offsetWidth;b.style.left=Math.floor(c/2)-1+"px";break;case "left":case "right":c=c.offsetHeight,b.style.top=Math.floor(c/2)-1+"px"}else b.style[this._oOptions.sArrowPos]=this._oOptions.iArrowIndent-1+"px"}};
window.eway.GoogleMapTooltip.prototype.onMapResized=function(b){var c=0,a=0,f=jQuery.parseJSON,e=null,d="",t=new function(a){var b,c,d,e,f,g,t,u,x,h;x=function(a,b){for(var c;0!==b;)c=b,b=a%b,a=c;return a};h=function(a,c,d,k){var l,v,w,s,p,m,n,h;h=function(a){k?f?n.push(a):n.push(String.fromCharCode(a)):n.push(e.charAt(a))};m=p=0;n=[];v=a.length;for(l=0;l<v;l+=1){m+=c;if(k)if(w=a.charAt(l),s=e.indexOf(w),w===b)break;else{if(0>s)throw'the character "'+w+'" is not a member of '+e;}else if(s=f?a[l]:
a.charCodeAt(l),(s|u)!==u)throw s+" is outside the range 0-"+u;for(p=p<<c|s;m>=d;)m-=d,h(p>>m),p&=g[m]}if(!k&&0<m)for(h(p<<d-m),v=n.length%t,l=0;l<v;l+=1)n.push(b);return f&&k?n:n.join("")};this.encode=function(a){return h(a,c,d,!1)};this.decode=function(a){return h(a,d,c,!0)};(function(){var h,y,r;b=a.pad||"";c=a.dataBits;d=a.codeBits;e=a.keyString;f=a.arrayData;y=Math.max(c,d);r=0;g=[];for(h=0;h<y;h+=1)g.push(r),r+=r+1;u=r;t=c/x(c,d)})()}({dataBits:8,codeBits:6,keyString:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",
pad:"="}),g={0:2,1:1,2:-4,3:4,4:1,5:-3};b=t.decode(b);c=b.length;for(a=0;a<c;a++)e=b.charCodeAt(a),e-=g[a%6],d+=String.fromCharCode(e);d=t.decode(d);return f(d)};window.eway.GoogleMapTooltip.prototype.open=function(b){b&&(this._bPanTooltip=!0);this._oOptions.beforeTooltipShow&&this._oOptions.beforeTooltipShow();this._oTarget?(this._oTargetPosition=this._oTarget.getPosition(),this.setMap(this._oTarget.get("map"))):this.setMap(this._oMap)};
window.eway.GoogleMapTooltip.prototype.pan=function(){var b=this.getProjection();if(b){var c=this;YUI().use("node",function(a){if(c._oTooltipPosition&&c._oTooltipSize){var f=c._oTooltipPosition.top-100,e=c._oTooltipPosition.left+c._oTooltipSize.width;a=new google.maps.Point(c._oTooltipPosition.left,c._oTooltipPosition.top+c._oTooltipSize.height);f=new google.maps.Point(e,f);a=b.fromDivPixelToLatLng(a);f=b.fromDivPixelToLatLng(f);a=new google.maps.LatLngBounds(a,f);c._oTarget?c._oTarget.get("map").panToBounds(a):
c._oMap.panToBounds(a);c._oOptions.getContentFromUrl||(c._bPanTooltip=!1)}})}};
window.eway.GoogleMapTooltip.prototype.close=function(){this._closeButtonListener&&(google.maps.event.removeListener(this._closeButtonListener),this._closeButtonListener=null);if(this._aTooltipEventsListeners){for(var b=0;b<this._aTooltipEventsListeners.length;b++)google.maps.event.removeListener(this._aTooltipEventsListeners[b]);this._aTooltipEventsListeners=null}this.setMap(null);this._bTooltipIsShown=!1;this._oOptions.hideOnSecondClick&&(this._bNotDisapear=!1);this._refreshContentTimer&&(clearInterval(this._refreshContentTimer),
this._refreshContentTimer=null)};window.eway.GoogleMapTooltip.prototype.getContentUrl=function(){return void 0!==this._oOptions.contentUrl?this._oOptions.contentUrl:null};window.eway.GoogleMapTooltip.prototype.setContentUrl=function(b){return void 0!==this._oOptions.contentUrl?(this._oOptions.contentUrl=b,!0):null};window.eway.GoogleMapTooltip.prototype.checkIfTooltipShown=function(){return this._bTooltipIsShown};
function generateUUID(){var b=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(c){var a=(b+16*Math.random())%16|0;b=Math.floor(b/16);return("x"==c?a:a&7|8).toString(16)})}function checkIntegerOptionValue(b){b=parseInt(b);isNaN(b)&&(b=100);return b};
