window.eway=window.eway||{};
window.eway.SimpleYuiTooltip=function(m){function w(a){void 0==a.stickOnTargetClick&&(a.stickOnTargetClick=!0);a.stickOnTargetClick=!!a.stickOnTargetClick;void 0==a.showOnMouseOver&&(a.showOnMouseOver=!0);a.showOnMouseOver=!!a.showOnMouseOver;a.showOnMouseOver||(a.stickOnTargetClick=!0);void 0==a.showCloseButton&&(a.showCloseButton=!1);a.stickOnTargetClick&&(a.showCloseButton=!0);a.showCloseButton=!!a.showCloseButton;a.handlePosition=a.handlePosition||"bottom";var d={top:1,bottom:1,left:1,right:1,
"top-left":1,"top-right":1,"bottom-left":1,"bottom-right":1,"left-top":1,"left-bottom":1,"right-top":1,"right-bottom":1};null==d[a.handlePosition]&&(a.handlePosition="bottom");d=a.handlePosition.split("-");a.sTooltipPos=d[0];a.sArrowPos=null;2==d.length&&(a.sArrowPos=d[1]);a.iArrowIndent=20;void 0==a.appearAfterTime&&(a.appearAfterTime=100);a.appearAfterTime=n(a.appearAfterTime);void 0==a.disappearAfterTime&&(a.disappearAfterTime=100);a.disappearAfterTime=n(a.disappearAfterTime);void 0==a.holdOnMouseOver&&
(a.holdOnMouseOver=!0);a.holdOnMouseOver=!!a.holdOnMouseOver;void 0==a.appearTime&&(a.appearTime=100);a.appearTime=n(a.appearTime);0==a.appearTime&&(a.appearTime=1);a.appearTime/=1E3;void 0==a.disappearTime&&(a.disappearTime=100);a.disappearTime=n(a.disappearTime);0==a.disappearTime&&(a.disappearTime=1);a.disappearTime/=1E3;void 0==a.hideArrow&&(a.hideArrow=!1);a.hideArrow=!!a.hideArrow;void 0===a.opacity&&(a.opacity=1);a.opacity=parseFloat(a.opacity);isNaN(a.opacity)&&(a.opacity=1);void 0===a.width&&
(a.width=150);a.width=parseFloat(a.width);isNaN(a.width)&&(a.width=150);0===a.width&&(a.width="auto");a.textAlign=a.textAlign||"left";d={left:1,center:1,right:1};null==d[a.textAlign]&&(a.textAlign="left");void 0!==a.noContentPadding&&(a.noContentPadding=!0)}function n(a){a=parseInt(a);isNaN(a)&&(a=100);return a}var l=null,t="",u="",e=function(){var a=(new Date).getTime();return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(d){var c=(a+16*Math.random())%16|0;a=Math.floor(a/16);return("x"==
d?c:c&7|8).toString(16)})}(),r="yui-tooltip-"+e;this.setTooltip=function(a,d){t=a;var c={};if("object"==typeof d&&null!==d)for(field in d)c[field]=d[field];w(c);YUI().use("node","event","transition","anim",function(a){function d(){g&&setTimeout(function(){g&&n()},c.appearAfterTime)}function n(){if(b){b.setStyle("visibility","visible");b.setStyle("opacity",0);var f=new a.Anim({node:b,from:{opacity:0},to:{opacity:c.opacity},duration:c.appearTime,easing:a.Easing.easeNone});f.on("tween",function(){g||
(f.destroy(),b&&(b.remove(),b=null))});f.run()}}function y(){if(b){var f=new a.Anim({node:b,to:{opacity:0},duration:c.disappearTime,easing:a.Easing.easeNone});f.on("end",function(){b&&(b.remove(),b=null)});f.on("tween",function(){g&&(f.destroy(),b&&(b.remove(),b=null))});f.run()}}function z(){if(a.one("#"+r))b=a.one("#"+r),b.setStyle("visibility","visible"),b.setStyle("width",c.width);else{b=a.Node.create("<DIV>");b.addClass("yui-tooltip yui-tooltip-"+c.sTooltipPos);b.setStyle("width",c.width);b.setAttrs({id:r});
var f="yui-tooltip-content";c.noContentPadding&&(f+="-nopadding");b.setHTML('<DIV id="yui-tooltip-'+e+'subarrow" class="yui-tooltip-subarrow yui-tooltip-subarrow-'+c.sTooltipPos+'"></DIV><DIV id="yui-tooltip-'+e+'arrow" class="yui-tooltip-arrow yui-tooltip-arrow-'+c.sTooltipPos+'"></DIV><DIV class="'+f+'" id="yui-tooltip-'+e+'content"><DIV id="yui-tooltip-'+e+'content-close-button" class="yui-tooltip-content-close-button"></DIV><DIV id="yui-tooltip-'+e+'content-text">'+t+"</DIV></DIV>");a.one("body").append(b);
c.showCloseButton?(a.one("#yui-tooltip-"+e+"content-close-button").on("click",function(a){setTimeout(function(){y()},c.disappearAfterTime);v=!1}),a.one("#yui-tooltip-"+e+"content-close-button").show()):a.one("#yui-tooltip-"+e+"content-close-button").hide();a.one("#yui-tooltip-"+e+"content").setStyle("textAlign",c.textAlign);d()}c.holdOnMouseOver&&(b.on("mouseleave",A),b.on("mousemove",w));p=b.get("offsetHeight");q=b.get("offsetWidth");s=parseInt(b.getStyle("paddingTop"))}function B(){var f=a.one("#yui-tooltip-"+
e+"arrow");if(c.hideArrow)f.hide();else{f.setStyle("top",null);f.setStyle("bottom",null);f.setStyle("right",null);f.setStyle("left",null);var b=a.one("#yui-tooltip-"+e+"content");if(null===c.sArrowPos)switch(c.sTooltipPos){case "bottom":case "top":b=b.get("offsetWidth");f.setStyle("left",Math.floor(b/2));break;case "left":case "right":b=b.get("offsetHeight"),f.setStyle("top",Math.floor(b/2))}else f.setStyle(c.sArrowPos,c.iArrowIndent)}}function C(){var b=a.one("#yui-tooltip-"+e+"subarrow");if(c.hideArrow)b.hide();
else{b.setStyle("top",null);b.setStyle("bottom",null);b.setStyle("right",null);b.setStyle("left",null);var d=a.one("#yui-tooltip-"+e+"content");if(null===c.sArrowPos)switch(c.sTooltipPos){case "bottom":case "top":d=d.get("offsetWidth");b.setStyle("left",Math.floor(d/2)-1);break;case "left":case "right":d=d.get("offsetHeight"),b.setStyle("top",Math.floor(d/2)-1)}else b.setStyle(c.sArrowPos,c.iArrowIndent-1)}}function D(){var a,d=l.get("offsetWidth"),e=l.get("offsetHeight");oElement=document.getElementById(u);
a=oElement.getBoundingClientRect();var h=document.body,k=document.documentElement,g=a.left+(window.pageXOffset||k.scrollLeft||h.scrollLeft)-(k.clientLeft||h.clientLeft||0);a=Math.round(a.top+(window.pageYOffset||k.scrollTop||h.scrollTop)-(k.clientTop||h.clientTop||0));g=Math.round(g);k=h=null;switch(c.sTooltipPos){case "left":h=a+e/2-p/2;k=g-q;break;case "right":h=a+e/2-p/2;k=g+d;break;case "top":h=a-p;k=g+d/2-q/2;break;case "bottom":h=a+e,k=g+d/2-q/2}switch(c.sArrowPos){case "left":k=k+q/2-c.iArrowIndent-
s;break;case "right":k=k-q/2+c.iArrowIndent+s;break;case "top":h=h+p/2-c.iArrowIndent-s;break;case "bottom":h=h-p/2+c.iArrowIndent+s}b.setStyle("left",k);b.setStyle("top",h)}function A(d){g?(g=!1,a.one("#"+r)&&(setTimeout(function(){x&&!v&&y()},c.disappearAfterTime),x=!0)):b&&(b.remove(),b=null)}function w(a){x=!1}"object"===typeof m&&null!==m&&(l=a.one(m),u=l.get("id"));"string"===typeof m&&(l=a.one("#"+m),u=m);e+=u;if(l){var x=!0,g=!0,b=null,p=null,q=null,s=null,v=!1;if(c.showOnMouseOver)l.on("simple-yui-tooltip|mousemove",
function(a){b||(g=!0,z(),B(),C(),D())});else v=!0;if(c.stickOnTargetClick)l.on("simple-yui-tooltip|click",function(a){v=!0;c.showOnMouseOver||b||(z(),B(),C(),D())});l.on("simple-yui-tooltip|mouseleave",A)}})};this.destroy=function(){l&&YUI().use("node","event",function(a){l.detach("simple-yui-tooltip|mousemove");l.detach("simple-yui-tooltip|mouseleave");l.detach("simple-yui-tooltip|click");(a=a.one("#"+r))&&a.remove()})};this.setContent=function(a){t=a;YUI().use("node",function(a){(a=a.one("#yui-tooltip-"+
e+"content"))&&a.setHTML(t)})}};
